---
- name: Deploy LAMP stack and Laravel application
  hosts: slave1
  tasks:
    - name: Transfer deployment script to server
      copy:
        src: lampdeploy.sh
        dest: /tmp/lampdeploy.sh
        mode: "0755"  # Ensure the script is executable

    - name: Execute deployment script
      shell: /tmp/lampdeploy.sh https://github.com/laravel/laravel.git mylaravelapp mylaraveldb db_user1 MyStrongPassword1 myapp development 192.168.50.15

    - name: Create cron job to check server's uptime
      cron:
        name: Check Uptime
        minute: 0
        hour: 0
        job: /path/to/script/or/command >> /var/log/uptime.log 2>&1
